config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#index'
  get 'notices/index', to: 'notices#index'

  resources :users, only: %i[index show edit update] do
    resources :operations, only: [:index] # ユーザーごとの勤務一覧
  end

  resources :notices, only: %i[index create edit update destroy]
  resources :calendars, only: [:index]
  resources :operations do
    member do
      patch :check_in   # 出勤
      patch :check_out  # 退勤
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.uniq.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_main_calendar.html.erb
<table>
  <thead>
    <tr>
      <th>ユーザー名</th>
      <% (start_date..end_date).each do |date| %>
        <th class="<%= 'saturday' if date.saturday? %> <%= 'sunday' if date.sunday? %>">
          <%= date.strftime('%m/%d (%a)') %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.name %>
        </td>
        <% (@start_date..@end_date).each do |date| %>
          <td>
            <% operation = user.operations.find { |op| (op.start_date..op.end_date).cover?(date) } %>
            <% if operation %>
              <div class="operation-cell <%= operation.category_name.downcase %>">
                <p><%= link_to operation.operation_info, operation_path(operation), class: "text-info" %></p>
                <p><%= operation.day_or_night.name %></p>
                <p><%= operation.work_content.name %></p>
              </div>
            <% else %>
              <p>休み</p>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_side_bar.html.erb
<div class="side-bar">
  <div class="side-bar-header">
    <!-- アプリ名 -->
    <p class="app-name">シェア助</p>

    <!-- ユーザー名とログアウトボタン -->
    <div class="user-info">
      <% if user_signed_in? %>
        <div class="user-name">
          <%= link_to current_user.name, edit_user_path(current_user), class: "user-link" %>
        </div>
        <div class="logout-btn">
          <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-danger' %>
        </div>
      <% else %>
        <div class="login-btn">
          <%= link_to "ログイン", new_user_session_path, class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="side-bar-footer">
    <div class="create-operation">
      <%= link_to '運行便の作成', new_operation_path, class: "btn btn-primary" %>
    </div>
    <div class="link-to-operations">
      <%= link_to "運行情報一覧", operations_path, class: "btn btn-success btn-sm" %>
    </div>
    <div class="link-to-user-operation">
      <%= link_to 'ユーザー情報一覧', user_path(current_user), class: "btn btn-primary" %>
    </div>
    <div class="notice">
      <%= link_to '連絡事項', notices_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>