config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#index'
  get 'notices/index', to: 'notices#index'

  resources :users, only: %i[index show edit update] do
    resources :operations, only: [:index] # ユーザーごとの勤務一覧
  end

  resources :notices, only: %i[index create edit update destroy]
  resources :calendars, only: [:index]
  resources :operations do
    member do
      patch :check_in   # 出勤
      patch :check_out  # 退勤
    end
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    # パラメータから開始日を取得し、デフォルトは今週の月曜日
    @start_date = params[:start_date] ? Date.parse(params[:start_date]) : Date.today.beginning_of_week

    # 開始日から6日後を終了日に設定
    @end_date = @start_date + 6.days
    @users = User.includes(:operations).all

    # 指定された期間内の運行情報を取得
    @operations = Operation.where('start_date <= ? AND end_date >= ?', @end_date, @start_date).includes(:user)
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_main_calendar.html.erb
<table>
  <thead>
    <tr>
      <th>ユーザー名</th>
      <% (start_date..end_date).each do |date| %>
        <th class="<%= 'saturday' if date.saturday? %> <%= 'sunday' if date.sunday? %>">
          <%= date.strftime('%m/%d (%a)') %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% User.all.each do |user| %>
      <tr>
        <td>
          <%= user.name %>
          
        </td>
        <% (start_date..end_date).each do |date| %>
          <td>
            <% operation = @operations.find { |op| op.user_id == user.id && (op.start_date..op.end_date).cover?(date) } %>
            <% if operation %>
              <p><%= link_to operation.operation_info, operation_path(operation), class: "text-info" %></p>
              <p><%= operation.day_or_night.name %></p>
              <p><%= operation.work_content.name %></p>
            <% else %>
              <p>休み</p>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/calendars/_side_bar.html.erb
<div class="side-bar-header">
  <!-- アプリ名 -->
  <p>
    シェア助
  </p>

  <!-- ユーザー名とログアウトボタン -->
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
    <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn' %>
  </div>
</div>

<div class="side-bar-footer">
  <div class="create-operation">
    <%= link_to '運行便を作成する', new_operation_path, class: "btn btn-primary" %>
  </div>
  <div class="link-to-operations">
    <%= link_to "運行情報一覧", operations_path, class: "btn btn-success btn-sm" %>
  </div>
</div>

app/views/calendars/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "shared/side_bar" %>
  </div>

  <div class="calendar-navigation">
    <div class="navigation-links">
    <%= link_to "先週", calendars_path(start_date: @start_date - 7.days), class: "btn btn-primary" %>
    <%= link_to "今週", calendars_path(start_date: Date.today.beginning_of_week), class: "btn btn-secondary" %>
    <%= link_to "来週", calendars_path(start_date: @start_date + 7.days), class: "btn btn-primary" %>
    </div>
  </div>

  <div class="calendar">
    <%= render "shared/main_calendar", start_date: @start_date, end_date: @end_date %>
  </div>
</div>

<div class="footer-text">
  <p>Copyright(C) Share-suke ALL RIGHTS RESERVED.</p>
</div>