config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#index'
  get 'notices/index', to: 'notices#index'

  resources :users, only: %i[index show edit update] do
    resources :operations, only: [:index] # ユーザーごとの勤務一覧
  end

  resources :notices, only: %i[index create edit update destroy]
  resources :calendars, only: [:index]
  resources :operations do
    member do
      patch :check_in   # 出勤
      patch :check_out  # 退勤
    end
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # ActiveHashとの関連付け
  belongs_to_active_hash :day_or_night
  belongs_to_active_hash :work_content
  belongs_to_active_hash :start_time
  belongs_to_active_hash :end_time

  # ユーザーとの関連付け
  belongs_to :user

  # その他のバリデーションなど
  validates :operation_info,  :start_date, :end_date, presence: true
  validates :day_or_night_id, :work_content_id, :start_time_id, :end_time_id,
            numericality: { other_than: 0, message: 'を選択してください' }
  validate :start_date_before_end_date
  validate :validate_date_overlap, on: :create

  # カテゴリ名を返すメソッド
  def category_name
    case work_content.name
    when '運行'
      'unko'
    when '代行'
      'daiko'
    when '覚え'
      'oboe'
    when '指導'
      'shido'
    else
      'default'
    end
  end

  private

  def start_date_before_end_date
    return unless start_date.present? && end_date.present? && start_date > end_date

    errors.add(:start_date, 'は終了日より前の日付にしてください')
  end

  def validate_date_overlap
    return unless start_date.present? && end_date.present?

    overlapping_operations = Operation.where(user_id: user_id)
                                      .where.not(id: id) # 自身は除外
                                      .where('start_date <= ? AND end_date >= ?', end_date, start_date)

    return unless overlapping_operations.exists?

    errors.add(:base, '同一ユーザー内で日付が重複しています')
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_user, only: [:index] # indexアクションで@userをセット
  before_action :set_operation, only: %i[show edit update destroy]
  def new
    @operation = Operation.new
    @operation.start_date ||= Date.today # デフォルト値を今日の日付に設定
  end

  def create
    @operation = Operation.new(operation_params)
    if @operation.save
      redirect_to calendars_path(start_date: @operation.start_date.beginning_of_week), notice: '運行情報が投稿されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @operations = if params[:user_id].present?
                    Operation.where(user_id: params[:user_id]).order(:start_date)
                  else
                    Operation.all.order(:start_date)
                  end

    @operation = @operations.first # ここで最初のデータを取得
  end

  def show
  end

  def edit
  end

  def update
    if @operation.update(operation_params)
      redirect_to @operation, notice: '運行情報を更新しました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @operation.destroy
    redirect_to calendars_path(start_date: @operation.start_date.beginning_of_week), notice: '運行情報を削除しました。'
  end

  private

  def set_operation
    @operation = Operation.find(params[:id])
  end

  def set_user
    @user = User.find_by(id: params[:user_id]) if params[:user_id].present?
  end

  def operation_params
    params.require(:operation).permit(:operation_info, :start_date, :end_date, :day_or_night_id, :work_content_id,
                                      :user_id, :memo)
  end
end

app/views/operations/edit.html.erb
<h1>運行情報を編集</h1>

<%= form_with model: @operation, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <div>
    <%= f.label :user_id, 'ユーザー' %>
    <%= f.collection_select :user_id, User.all, :id, :name, prompt: '選択してください' %>
  </div>

  <div>
    <%= f.label :start_date, '開始日' %>
    <%= f.date_field :start_date, class: 'form-control' %>
  </div>

  <div>
    <%= f.label :end_date, '終了日' %>
    <%= f.date_field :end_date, class: 'form-control' %>
  </div>

  <div>
    <%= f.label :operation_info, '運行情報' %>
    <%= f.text_field :operation_info %>
  </div>

  <div>
    <%= f.label :day_or_night_id, '昼/夜' %>
    <%= f.collection_select :day_or_night_id, DayOrNight.all, :id, :name, prompt: '選択してください' %>
  </div>

  <div>
    <%= f.label :work_content_id, '業務内容' %>
    <%= f.collection_select :work_content_id, WorkContent.all, :id, :name, prompt: '選択してください' %>
  </div>

  <div>
    <%= f.label :memo, 'メモ' %>
    <%= f.text_area :memo, class: 'form-control', rows: 3, placeholder: '自由にメモを記入してください' %>
  </div>

  <%= f.submit '更新', class: "btn btn-update" %>
<% end %>

<%= link_to "キャンセル", operation_path(@operation), class: "btn btn-secondary" %>

<div class="footer-text">
  <p>Copyright(C) Share-suke ALL RIGHTS RESERVED.</p>
</div>

app/views/operations/index.html.erb
<h1>運行情報一覧</h1>

<!-- 全ユーザーの一覧を表示 -->
<div class="user-list">
  <h2>ユーザー別運行情報</h2>
  <%= form_with url: operations_path, method: :get, local: true do %>
    <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :name), include_blank: "全てのユーザー" %>
    <%= submit_tag "検索", class: "btn btn-primary" %>
  <% end %>
</div>

<!-- 運行情報テーブル -->
<table>
  <thead>
    <tr>
      <th>ユーザー名</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>運行情報</th>
      <th>時間帯</th>
      <th>業務内容</th>
      <th>メモ</th>
    </tr>
  </thead>
  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.user.name %></td>
        <td><%= operation.start_date %></td>
        <td><%= operation.end_date %></td>
        <td><%= operation.operation_info %></td>
        <td><%= operation.day_or_night.name %></td>
        <td><%= operation.work_content.name %></td>
        <td><%= operation.memo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @operation && @operation.start_date.present? %>
  <%= link_to 'カレンダーに戻る', calendars_path, class: 'btn btn-secondary' %>
<% else %>
  <p>運行情報がありません。</p>
<% end %>

<div class="footer-text">
  <p>Copyright(C) Share-suke ALL RIGHTS RESERVED.</p>
</div>

app/views/operations/new.html.erb
<h1>運行情報を作成</h1>

<%= form_with model: @operation, local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>

  <div>
    <%= f.label :user_id, 'ユーザー' %>
    <%= f.collection_select :user_id, User.all, :id, :name, prompt: '選択してください' %>
  </div>

  <div>
    <%= f.label :start_date, '開始日' %>
    <%= f.date_field :start_date, class: 'form-control' %>
  </div>

  <div>
    <%= f.label :end_date, '終了日' %>
    <%= f.date_field :end_date, class: 'form-control' %>
  </div>

  <div>
    <%= f.label :start_time_id, "開始時間" %>
    <%= f.collection_select :start_time_id, TimeSlot.all, :id, :name, prompt: "選択してください" %>
  </div>

  <div>
    <%= f.label :end_time_id, "終了時間" %>
    <%= f.collection_select :end_time_id, TimeSlot.all, :id, :name, prompt: "選択してください" %>
  </div>

  <div>
    <%= f.label :operation_info, '運行情報' %>
    <%= f.text_field :operation_info %>
  </div>

  <div>
    <%= f.label :day_or_night_id, '昼/夜' %>
    <%= f.collection_select :day_or_night_id, DayOrNight.all, :id, :name, prompt: '選択してください' %>
  </div>

  <div>
    <%= f.label :work_content_id, '業務内容' %>
    <%= f.collection_select :work_content_id, WorkContent.all, :id, :name, prompt: '選択してください' %>
  </div>

  <div>
  <%= f.label :memo, 'メモ' %>
  <%= f.text_area :memo, class: 'form-control', rows: 3, placeholder: '自由にメモを記入してください' %>
  </div>

  <%= f.submit '作成', class: "btn btn-create" %>
<% end %>

<%= link_to 'カレンダーに戻る', calendars_path(start_date: @operation.start_date.beginning_of_week), class: 'btn btn-secondary' %>

<div class="footer-text">
  <p>Copyright(C) Share-suke ALL RIGHTS RESERVED.</p>
</div>

app/views/operations/show.html.erb
<div class="operation-details">
  <h1>運行情報詳細</h1>
  <p>ユーザー名: <%= @operation.user.name %></p>
  <p>日付: <%= @operation.start_date %> ～ <%= @operation.end_date %></p>
  <p>開始時間: <%= @operation.start_time.name %></p>
  <p>終了時間: <%= @operation.end_time.name %></p>
  <p>運行情報: <%= @operation.operation_info %></p>
  <p>昼/夜: <%= @operation.day_or_night.name %></p>
  <p>業務内容: <%= @operation.work_content.name %></p>
  <p>メモ: <%= @operation.memo %></p>

  <%= link_to 'カレンダーに戻る', calendars_path(start_date: @operation.start_date.beginning_of_week), class: 'btn btn-secondary' %>
  <%= link_to "編集", edit_operation_path(@operation), class: "btn btn-primary" %>
  <%= link_to '削除', operation_path(@operation), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
</div>

<div class="footer-text">
  <p>Copyright(C) Share-suke ALL RIGHTS RESERVED.</p>
</div>